# https://rancher.com/docs/k3s/latest/en/advanced/#running-k3d-k3s-in-docker-and-docker-compose
# https://github.com/k3s-io/k3s/blob/master/docker-compose.yml

version: '3'
services:

  server:
    env_file:
      - ./.env
    image: "rancher/k3s:v1.21.12-k3s1"
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443 # Kubernetes API Server
    - 80:80 # Ingress controller port 80
    - 443:443 # Ingress controller port 443

  agent:
    env_file:
      - ./.env
    image: "rancher/k3s:v1.21.12-k3s1"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:?err}

volumes:
  k3s-server: {}